---
title: "p8105_hw1_ao2671"
author: "Anna Ostropolets"
date: "9/13/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

```{r chunk1, echo=FALSE, message = FALSE, warning=FALSE}
# creating a dataframe with a sample from normal distribution, logical, cahracter and factor vectors
library(tidyverse)
data_frame = tibble(

  vec_norm_distr = rnorm(10), 
  
  vec_logical = vec_norm_distr>0,
  
  vec_char =  c ("first","second","third","forth","fifth","sixth","seventh","eighth","ninth","tenth"),
  
  vec_factor = factor(c("green","black", "blue", "black", "blue", "blue", "green","blue", "green","green"))
  
)

# test if can take the mean of variables in the dataframe

distrib_mean = mean(data_frame$vec_norm_distr)

logical_mean = mean(data_frame$vec_logical)

char_mean = mean(data_frame$vec_char) 

factor_mean = mean(data_frame$vec_factor) 

# print the output of the dataframe
data_frame

# answers to homework question 1
cat('The mean of samples from distribution',distrib_mean, ';\n The mean of logical vector',logical_mean, '; \n The mean of character vector',char_mean,  ';\n The mean of factor vector',factor_mean)
cat('Answer: We can take the mean of logical or numberic vector but not of character of factor vectors')
```


```{r chunk1.2, eval=FALSE}

# convert logical vector to numeric
as.numeric(data_frame$vec_logical)
# convert character vector to numeric
as.numeric(data_frame$vec_char)
# convert factor vector to numeric
as.numeric(data_frame$vec_factor)

#logical variables can be converted to numbers where 1 is TRUE and 0 is FALSE, 
#factor can be converted to numbers according to the number of levels 
#and character variables cannot be converted to numbers. 
#This is why we can take the mean of logical variable but not for character variables. 
#Logical variables have to be converted to numeric prior to taking the mean
```

```{r chunk2, message = FALSE, warning=FALSE}
# convert logical vector 
logical_to_numeric = as.numeric(data_frame$vec_logical)*data_frame$vec_norm_distr
logical_to_factor = as.factor(data_frame$vec_logical)*data_frame$vec_norm_distr
logical_to_factor_to_numeric = as.numeric(as.factor(data_frame$vec_logical))*data_frame$vec_norm_distr


logical_to_numeric
logical_to_factor
logical_to_factor_to_numeric
```

### Problem 2

```{r chunk3, echo=FALSE, warning=FALSE}

# load the data and explore it
library("palmerpenguins")
data("penguins", package = "palmerpenguins")
# head(penguins)

# calculate number of observations (rows, pinguins) and features (columns)
ping_cnt = nrow(penguins)
feature_cnt = ncol(penguins)

# calculate numer of species and islands
ping_species_cnt = count(distinct(penguins, species))
island_cnt = count(distinct(penguins, island))

# get the list of islands and species names
island_list = paste(levels(head(penguins)$island), collapse=', ')
species_list = paste(levels(head(penguins)$species), collapse=', ')

# filter NA and compute mean flipper lenght
mean_flipper = mean(filter(penguins,!is.na(flipper_length_mm))$flipper_length_mm)


# description of dataset
paste('The dataset has ', feature_cnt, ' columns and contains the information about ', ping_cnt, ' pinguings from ', ping_species_cnt,' species of pinguings ',
' living on ', island_cnt, ' islands. The date specifies their ',colnames(penguins)[7], ' and ', colnames(penguins)[8], 
'as well as bill characteristics. Islands include ', island_list, ' and species include ', species_list, 
'Mean flipper length is ', mean_flipper)

# plot bill and flipper lenght and group them by species
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species))  + 
  labs(title="Correlation of bill and flipper length",x="Bill, mm", y = "Flipper, mm") +
  geom_point()
ggsave("scatterplot.jpg", height = 4, width = 6)

```


